config/routes.rb
Rails.application.routes.draw do
  get 'sobre_nosotros/index'
  get 'contacto/index'
  get 'panel_administracion/index'
  resources :articulos
  resources :ropas
  resources :tienda_ropa
  resources :tienda_articulo
  resources :panel_administracion
  resources :contacto
  resources :sobre_nosotros
  get 'inicio/home'
  root :to => "inicio#home"


  get 'signup', to: 'usuarios#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


  resources :usuarios
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ropa.rb
class Ropa < ApplicationRecord
    has_one_attached:image

end

app/controllers/ropas_controller.rb
class RopasController < ApplicationController
  before_action :set_ropa, only: [:show, :edit, :update, :destroy]

  # GET /ropas
  # GET /ropas.json
  def index
    #@ropas = Ropa.all
    if params[:title].blank?  
      @ropas = Ropa.all  
    else  
      @parameter = params[:title].downcase  
      @prendas = Prenda.all.where("lower(nombre) LIKE :title", title: "%#{@parameter}%")  
    end  
  end

  # GET /ropas/1
  # GET /ropas/1.json
  def show
  end

  # GET /ropas/new
  def new
    @ropa = Ropa.new
  end

  # GET /ropas/1/edit
  def edit
  end

  # POST /ropas
  # POST /ropas.json
  def create
    @ropa = Ropa.new(ropa_params)
    @ropa.image.attach(ropa_params[:image])

      if @ropa.save
        flash[:success] = "Prenda creado correctamente."
        redirect_to @ropa
      else
        render 'new'
      end
    end
    / respond_to do |format|
      if @ropa.save
        format.html { redirect_to @ropa, notice: 'Ropa was successfully created.' }
        format.json { render :show, status: :created, location: @ropa }
      else
        format.html { render :new }
        format.json { render json: @ropa.errors, status: :unprocessable_entity }
      end
    end
  end
  /

  # PATCH/PUT /ropas/1
  # PATCH/PUT /ropas/1.json
  def update
    @ropa.image.purge
    @ropa.image.attach(ropa_params[:image])
    respond_to do |format|
      if @ropa.update(ropa_params)
        format.html { redirect_to @ropa, notice: 'Ropa was successfully updated.' }
        format.json { render :show, status: :ok, location: @ropa }
      else
        format.html { render :edit }
        format.json { render json: @ropa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ropas/1
  # DELETE /ropas/1.json
  def destroy
    @ropa.destroy
    respond_to do |format|
      format.html { redirect_to ropas_url, notice: 'Ropa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ropa
      @ropa = Ropa.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ropa_params
      params.require(:ropa).permit(:nombre, :precio, :descripcion, :image)
    end
end

app/helpers/ropas_helper.rb
module RopasHelper
end

app/views/ropas/_form.html.erb
<div class="container">
<%= form_with(model: ropa) do |form| %>
  <% if ropa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ropa.errors.count, "error") %> prohibited this ropa from being saved:</h2>

      <ul>
        <% ropa.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.text_field :precio %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/ropas/edit.html.erb
<div class="container">
<h1>Editar Prenda</h1>
<br>


<%= render 'form', ropa: @ropa %>

<%= link_to 'Ver', @ropa %> |
<%= link_to 'Volver', ropas_path %>
</div>

app/views/ropas/index.html.erb
<p id="notice"><%= notice %></p>
<div style="margin-left: 2em;">
<h1>Toda nuestra ropa</h1>
<p> Bienvenido al panel de gestión de la ropa, aquí podrá crear, modificar y eliminar las prendas deportivas</p>
<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Descripcion</th>
      <th>Imagen</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @ropas.each do |ropa| %>
      <tr>
        <td><%= ropa.nombre %></td>
        <td><%= ropa.precio %></td>
        <td><%= ropa.descripcion %></td>
        <td><% if ropa.image.attached? %>
        <img src="<%= url_for(ropa.image)  %>" class="img-rounded img-responsive" alt="Product view">
      <% end %></td>
        <td class="enlaceboton"><%= link_to 'Ver', ropa %></td>
        <td class="enlaceboton"><%= link_to 'Editar', edit_ropa_path(ropa) %></td>
        <td class="enlaceboton"><%= link_to 'Borrar', ropa, method: :destroy, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<a class="enlaceboton" href="/ropas/new" role="button">Crear prenda</a>
<a class="enlaceboton" href="/panel_administracion" role="button">Página principal</a>

</div>

app/views/ropas/new.html.erb
<h1>New Ropa</h1>

<%= render 'form', ropa: @ropa %>

<%= link_to 'Back', ropas_path %>

app/views/ropas/show.html.erb
<div class="container-fluid text-center">
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @ropa.nombre %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @ropa.precio%> €
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @ropa.descripcion %>
</p>

<p>
<% if @ropa.image.attached? %>
<p>
<strong>Imagen:</strong>
<br>
<%= image_tag @ropa.image %>
</p>
<% end %>
</p>
<br>
<a class="enlaceboton" href="/tienda_ropa">Volver</a>

</div>