config/routes.rb
Rails.application.routes.draw do
  get 'sobre_nosotros/index'
  get 'contacto/index'
  get 'panel_administracion/index'
  resources :articulos
  resources :ropas
  resources :tienda_ropa
  resources :tienda_articulo
  resources :panel_administracion
  resources :contacto
  resources :sobre_nosotros
  get 'inicio/home'
  root :to => "inicio#home"


  get 'signup', to: 'usuarios#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


  resources :usuarios
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/usuario.rb
class Usuario < ApplicationRecord
	has_secure_password
	has_one_attached:image
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]
  
  
  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)
    @usuario.image.attach(usuario_params[:image])

    if @usuario.save
      flash[:success] = "El usuario fue agregado correctamente."
      redirect_to @usuario
    else
      render 'new'
    end

=begin
    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'El usuario fue agregado correctamente.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
=end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    @usuario.image.purge
    @usuario.image.attach(usuario_params[:image])

    if @usuario.update(usuario_params)
      flash[:info] = "El usuario fue actualizado correctamente."
      redirect_to @usuario
    else
      render 'edit'
    end

=begin
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'El usuario fue actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
=end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    flash[:success] = "El usuario fue eliminado correctamente."
    redirect_to usuarios_url

=begin
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'El usuario fue eliminado correctamente.' }
      format.json { head :no_content }
    end
=end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :apellidos, :categoria, :rol, :image, :datos, :email, :password)
    end

    def access
      rol = session[:usuario_rol].to_s.downcase
      if rol != "admin" || session[:usuario_id] == nil
        redirect_to root_url
      end
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="form-group">
    <%= form.label :apellidos %>
    <%= form.text_field :apellidos %>
  </div>


  <div class="form-group">
    <%= form.label :rol %>
    <%= form.text_field :rol %>
  </div>


  <div class="form-group">
    <%= form.label :datos %>
    <%= form.text_area :datos %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<div class="container"><h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>
</div>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Usuarios</h1>
  

  <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Apellidos</th>
        <th>Rol</th>
        <th>Datos</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @usuarios.each do |usuario| %>
        <tr>
          <td><%= usuario.nombre %></td>
          <td><%= usuario.apellidos %></td>
          <td><%= usuario.rol %></td>
          <td><%= usuario.datos %></td>
          <td><%= usuario.email %></td>
          <td><%= link_to 'Ver', usuario %></td>
          <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
          <td><%= link_to 'Eliminar', usuario, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <a class="enlaceboton" href="/usuarios/new" role="button">Nuevo usuario</a>
  <a class="enlaceboton" href="/panel_administracion" role="button">Página principal</a>
</div>

app/views/usuarios/new.html.erb
<div class="container">
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>
</div>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid text-center">
<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @usuario.apellidos %>
</p>

<p>
  <strong>Categoria:</strong>
  <%= @usuario.categoria %>
</p>

<p>
  <strong>Rol:</strong>
  <%= @usuario.rol %>
</p>

<p>
<% if @usuario.image.attached? %>
<p>
<strong>Image:</strong>
<br>
<%= image_tag @usuario.image %>
</p>
<% end %>
</p>

<p>
  <strong>Datos:</strong>
  <%= @usuario.datos %>
</p>

<%= link_to 'Editar', edit_usuario_path(@usuario) %> |
<%= link_to 'Volver', usuarios_path %>
</div>