config/routes.rb
Rails.application.routes.draw do
  get 'sobre_nosotros/index'
  get 'contacto/index'
  get 'panel_administracion/index'
  resources :articulos
  resources :ropas
  resources :tienda_ropa
  resources :tienda_articulo
  resources :panel_administracion
  resources :contacto
  resources :sobre_nosotros
  get 'inicio/home'
  root :to => "inicio#home"


  get 'signup', to: 'usuarios#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'


  resources :usuarios
  resources :sessions, only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/articulo.rb
class Articulo < ApplicationRecord
    has_one_attached:image
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  before_action :set_articulo, only: [:show, :edit, :update, :destroy]

  # GET /articulos
  # GET /articulos.json
  def index
    if params[:title].blank?  
      @articulos = Articulo.all  
    else 
      @parameter = params[:title].downcase  
      @prendas = Prenda.all.where("lower(nombre) LIKE :title", title: "%#{@parameter}%")  
    end
  end

  # GET /articulos/1
  # GET /articulos/1.json
  def show
  end

  # GET /articulos/new
  def new
    @articulo = Articulo.new
  end

  # GET /articulos/1/edit
  def edit
  end

  # POST /articulos
  # POST /articulos.json
  def create
    @articulo = Articulo.new(articulo_params)
    @articulo.image.attach(articulo_params[:image])
    
    if @articulo.save
    flash[:success] = "Articulo creado correctamente."
        redirect_to @articulo
      else
        render 'new'
      end
    end  
    /respond_to do |format|
      if @articulo.save
        format.html { redirect_to @articulo, notice: 'Articulo was successfully created.' }
        format.json { render :show, status: :created, location: @articulo }
      else
        format.html { render :new }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end
  /

  # PATCH/PUT /articulos/1
  # PATCH/PUT /articulos/1.json
  def update
    @articulo.image.purge
    @articulo.image.attach(articulo_params[:image])
    respond_to do |format|
      if @articulo.update(articulo_params)
        format.html { redirect_to @articulo, notice: 'Articulo was successfully updated.' }
        format.json { render :show, status: :ok, location: @articulo }
      else
        format.html { render :edit }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articulos/1
  # DELETE /articulos/1.json
  def destroy
    @articulo.destroy
    respond_to do |format|
      format.html { redirect_to articulos_url, notice: 'Articulo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articulo
      @articulo = Articulo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def articulo_params
      params.require(:articulo).permit(:nombre, :precio, :descripcion, :image)
    end
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/views/articulos/_form.html.erb
<div class="container">

<%= form_with(model: articulo) do |form| %>
  <% if articulo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(articulo.errors.count, "error") %> prohibited this articulo from being saved:</h2>

      <ul>
        <% articulo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.text_field :precio %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/articulos/edit.html.erb
<div class="container">
<h1>Editando artículo</h1>

<%= render 'form', articulo: @articulo %>

<%= link_to 'Ver', @articulo %> |
<%= link_to 'Volver', articulos_path %>
</div>

app/views/articulos/index.html.erb
<p id="notice"><%= notice %></p>
<div style="margin-left: 2em;">
<h1>Nuestro Material</h1>
<p>Bienvenido a la gestion de los artículos, aquí podrá crear, eliminar y modificar el material deportivo</p>

<table class="table table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Nombre</th>
      <th>Precio</th>
      <th>Descripcion</th>
      <th>Imagen</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @articulos.each do |articulo| %>
      <tr>
        <td><%= articulo.nombre %></td>
        <td><%= articulo.precio %> €</td>
        <td><%= articulo.descripcion %></td>
        <td><% if articulo.image.attached? %>
        <img src="<%= url_for(articulo.image)  %>" class="img-rounded img-responsive" alt="Product view">
      <% end %></td>
        <td class="enlaceboton"><%= link_to 'Ver', articulo %></td>
        <td class="enlaceboton"><%= link_to 'Editar', edit_articulo_path(articulo) %></td>
        <td class="enlaceboton"><%= link_to 'Eliminar', articulo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<a class="enlaceboton" href="/articulos/new" role="button">Crear artículo</a>
<a class="enlaceboton" href="/panel_administracion" role="button">Página principal</a>
</div>

app/views/articulos/new.html.erb
<h1>New Articulo</h1>

<%= render 'form', articulo: @articulo %>

<%= link_to 'Back', articulos_path %>

app/views/articulos/show.html.erb
<div class="container-fluid text-center">
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @articulo.nombre %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @articulo.precio %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @articulo.descripcion %>
</p>

<p>
<% if @articulo.image.attached? %>
<p>
<strong>Image:</strong>
<br>
<%= image_tag @articulo.image %>
</p>
<% end %>
</p>

<br>
<a class="enlaceboton" href="/tienda_ropa">Volver</a>
</div>